// apps/inertia-svelte/resources/js/Shared/Nav.svelte
<script>
  import { inertia, page } from '@inertiajs/svelte'
  $: nav = $page.props.nav ?? []
</script>

<header>
  <nav aria-label="Contract pages">
    <a href="/" use:inertia data-testid="nav-home">Home</a>
    {#each nav as item (item.key)}
      <a href={item.href} use:inertia data-testid={`nav-${item.key}`}>{item.label}</a>
    {/each}
  </nav>
</header>

// apps/inertia-react/resources/js/Shared/Nav.jsx
import { Link, usePage } from '@inertiajs/react'

export default function Nav() {
  const nav = usePage().props.nav ?? []
  return (
    <header>
      <nav aria-label="Contract pages">
        <Link href="/" data-testid="nav-home">Home</Link>
        {nav.map((item) => (
          <Link key={item.key} href={item.href} data-testid={`nav-${item.key}`}>
            {item.label}
          </Link>
        ))}
      </nav>
    </header>
  )
}
