// apps/inertia-vue/resources/js/Shared/Nav.vue
<script setup>
import { Link, usePage } from '@inertiajs/vue3'
const nav = usePage().props.nav ?? []
</script>

<template>
  <header>
    <nav aria-label="Contract pages">
      <Link href="/" data-testid="nav-home">Home</Link>
      <Link
        v-for="item in nav"
        :key="item.key"
        :href="item.href"
        :data-testid="`nav-${item.key}`"
      >{{ item.label }}</Link>
    </nav>
  </header>
</template>

// apps/inertia-react/resources/js/Shared/Nav.jsx
import { Link, usePage } from '@inertiajs/react'

export default function Nav() {
  const nav = usePage().props.nav ?? []
  return (
    <header>
      <nav aria-label="Contract pages">
        <Link href="/" data-testid="nav-home">Home</Link>
        {nav.map((item) => (
          <Link key={item.key} href={item.href} data-testid={`nav-${item.key}`}>
            {item.label}
          </Link>
        ))}
      </nav>
    </header>
  )
}
